### PR TITLE
Add patch for 9.23

### LINKED ISSUE #38: Add patch for 9.23
https://bugs.winehq.org/show_bug.cgi?id=48138

when available

### PR DESCRIPTION
**Pull request by cosarara**
Fixes #38

### CODE REVIEW

**Comment by MortalGoddess** [comment]
I am having an infinite bug splat loop when I add the patch to my own build

**Comment by cosarara** [comment]
> I am having an infinite bug splat loop when I add the patch to my own build

I'm afraid I don't have the knowledge to debug that, I have simply added the patch to the PKGBUILD. I know it works for me and other people, but maybe there is more to fix depending on the environment. The technical details are probably better suited for the bug report at https://bugs.winehq.org/show_bug.cgi?id=48138

**Comment by leaty** [comment]
@MortalGoddess does it occur during client launch or game launch?

**Comment by M-Reimer** [comment]
Can you please adapt this to the current state on the "master" branch?
I want to go with Wine 4.20 if we have to touch the PKGBUILD anyway.

**Comment by MortalGoddess** [comment]
@leaty this occurs on client launch with the patch being applied to my own PKGBUILD as well. Results in a PKG that is identical to this one

**Comment by M-Reimer** [comment]
Somewhere in the process sha512 sums got lost. I'll fix that later

**Comment by leaty** [comment]
@MortalGoddess I had a bugsplat the first time I opened the client, fixed it by reinitializing the wine prefix. I don't know the official way but I just ran `WINEPREFIX=~/games/league-of-legends/ winetricks` which executes winetricks using system wine. Let it open, close it, relaunch league using wine-lol.

**Pull request merged**
