### PR TITLE
Support for .rpm, .deb and tarballs from Dockerfile

### PR DESCRIPTION
**Pull request by wiryfuture**
Summary:
---
The dockerfile now creates packages for arch, debian and fedora based distros, in the form of pkg.tar.zst, .deb, .rpm and tarballs.

Why is there some unused .spec files and an unused build stage?
---
I don't like using fpm for fedora builds, but it's the easiest way of doing it until I figure out how rpmbuild works. The 'unused' build stage is the rpmbuild build stage that I am currently working on.

Does adding more package types take much longer?
---
No! The binaries are only compiled at the arch package phase and are then reused for the other packages, meaning that time spent creating them takes as long as it takes for your container runtime to download the necessary build tools and then use the package builder tool to wrap the binary in whatever file type the packages are stored as.

Can more package types be added?
---
If a package builder supports using a precompiled binary, it can easily be added in.

### CODE REVIEW

**Comment by M-Reimer** [comment]
Would you mind moving your new subdirectories below "contrib" to an grouping directory "docker" to clean this up a bit?

Thanks for figuring this out. Now I just have to make the RPM build work without docker to include this into my release process and put the built packages on my server for other users to download.

**Comment by wiryfuture** [comment]
Sure, will do. 
I might set up a CI/CD server on my metal, but I'm also wondering about whether you could set up a Github action to build the packages then show them in the release page on the repo, should be really easy with the Dockerfile 😀
I'll report on that later I'll check using my fork 🙏🏻

**Comment by M-Reimer** [comment]
At least for Arch I'm signing the final files and before signing with my GPG key, I prefer to have this built on my dedicated build VM.

I prefer VM solutions as it never requires me to enter my host root password anywhere while docker does. Just provides way better isolation between my host and my build machine.

**Comment by wiryfuture** [comment]
How did you use Docker? I use it everyday without ever typing in my root password 😁

**Comment by wiryfuture** [comment]
Also, I've moved the Docker stuff into its own folder, you're free to merge now if you want to 👍

**Pull request merged**
